### ISSUE TITLE
Can I use this API to send Direct Message to another user? 

### ISSUE THREAD

**Issue by joshuabezaleel** [ahmdrz/goinsta#101]

**Comment by ahmdrz** [comment]
Hi , Do you want it to use as text message sender ?
Many days ago I implement it just for text message and send ❤ in direct.

**Comment by joshuabezaleel** [comment]
@ahmdrz yeah, just a simple plain text to send as a direct message to another user would be nice
do you have any example/doc on how to do this? because i thought from the documentation that this is just can be used to retrieve all the direct messages in our inbox, and not can be used to send a reply

**Comment by ahmdrz** [comment]
I have to see my old codes.
I will show you how to use it.

Regards

On Mar 13, 2018 17:55, joshuabezaleel <notifications@github.com> wrote:

@ahmdrz<https://github.com/ahmdrz> yeah, just a simple plain text to send as a direct message to another user would be nice
do you have any example/doc on how to do this? because i thought from the documentation that this is just can be used to retrieve all the direct messages in our inbox, and not can be used to send a reply

**Comment by ahmdrz** [comment]
Sorry :)
I forgot this one [DirectMessage](https://github.com/ahmdrz/goinsta/blob/master/goinsta.go#L1197)

**Comment by joshuabezaleel** [comment]
@ahmdrz yeah I think this is the one I'm looking for. Thank you very much.
But then my question continues to how to get all the Direct Messages in our inbox because I thought this method is used to retrieve the direct messages, not to send it.

**Comment by ahmdrz** [comment]
Does [this](https://github.com/ahmdrz/goinsta/blob/master/goinsta.go#L965) satisfy your need ?

**Comment by joshuabezaleel** [comment]
@ahmdrz ahahaha, thank you very much for coping up with me. appreciate it. 
all the best!
