### ISSUE TITLE
upload media

### ISSUE THREAD

**Issue by codenoid** [ahmdrz/goinsta#119]
hi, i'm new in go (and goinsta), can i upload media (with caption) with goinsta ?, thank you

**Comment by themester** [comment]
At this moment no. We are working on it.

**Comment by ahmdrz** [comment]
Added on https://github.com/ahmdrz/goinsta/blob/master/media.go#L798

**Comment by gurupras** [comment]
Just a quick follow up question since I didn't think it warranted a separate issue.
Is it possible to upload multiple photos as part of an Instagram post? 

The linked code https://github.com/ahmdrz/goinsta/blob/master/media.go#L798 seems to be taking in an `io.Reader` object which, to me, seems like it represents just one photo/file.

**Comment by wilsontamarozzi** [comment]
Is it possible to upload videos as well?

So I've noticed some tools have limitation for uploading videos.
