### ISSUE TITLE
check if user is following me

### ISSUE THREAD

**Issue by tcurdt** [ahmdrz/goinsta#121]
I am logged in and I am calling `insta.Profiles.ByName(account)` of another user.
I would like to know if that user is following me or not.

```
user, err := insta.Profiles.ByName(account)
// user.Sync()
fmt.Printf("friendship=%+v\n", user.Friendship)
```
While I know for sure the user is following me the friendship looks like this:

```
friendship={IncomingRequest:false FollowedBy:false OutgoingRequest:false Following:false Blocking:false IsPrivate:false Muting:false IsMutingReel:false}
```

What am I missing? Shouldn't it have `Following:true`?

Also: While it does not seem to affect the friendship I am not sure whether I need to call `Sync()` or not.

**Comment by themester** [comment]
You can use [FriendShip](https://godoc.org/github.com/ahmdrz/goinsta#User.FriendShip)

We don't set FriendShip call by default when you got a user because Instagram blocks if you do x requests in a row in a minute.

Sorry for the delay. If you want to solve a question fastly you can contact me in telegram at @themester

**Comment by tcurdt** [comment]
@themester `Sync` and `FriendShip` now that's confusing. But I got it working now. Thanks!

**Comment by themester** [comment]
@tcurdt Sync is used to get new user info. This function have been implemented because in most calls you got a partial information of user. For example when you got Stories from any user, the User inside the Items does not have complete fields filled. In this case to fill all fields you can use Sync.

**Comment by tcurdt** [comment]
@themester The idea is clear - just not when to use what. I tried `Sync` and expected that `FriendShip` also gets filled. It didn't even cross my mind to search for another function that fills just the `FriendShip` field.

**Comment by themester** [comment]
Um, thats true but I marked the problem before. If you want to get 100 users you are going to make 200 requests, 2 per user and this method waste your requests per minute.

**Comment by themester** [comment]
We are thinking to make a minimal or commfortable API (in a subpackage) with the intention to reduce the fields in the structures and make a more easy API. This package will be useful if you want to make simple things like get new user feed media. You don't want to know `VideoDuration` or `HasSharedToFb` you just want to download the media and know if there are any new media.

**Comment by themester** [comment]
@tcurdt Good idea. I am going to think how to implement something like this. Thanks for your contribution!
