### ISSUE TITLE
Login never succeeds, always checkpoint_challenge_required

### ISSUE THREAD

**Issue by pandoratoolbox** [ahmdrz/goinsta#188]
Hello, I've been trying to test goinsta with this code:

```
	user := goinsta.New("user", "pass")
	if err := user.Login(); err != nil {
		fmt.Println(err)
	}
	target, err := user.Profiles.ByName("targetuser")
	if err != nil {
		fmt.Println(err)
	}
	err = target.Follow()
	if err != nil {
		fmt.Println(err)
	}
```

Every time I run this code, it will say '**fail: challenge_required (checkpoint_challenge_required)**'

I log in to my account through my normal browser and click 'This was me;', but when I try to run the code again it prompts another checkpoint challenge. Is there a solution for this? Thanks

**Comment by gurupras** [comment]
You're probably running into this due to Instagram deprecating older versions of the app or something along those lines. I'll try to write up a PR for resolving this, but for now, you could copy over constants from: https://github.com/mgp25/Instagram-API/blob/master/src/Constants.php

**Comment by danicheeta** [comment]
you have to login instagram web application, go to settings in your profile, disable your account under reason of "I need to take a break", then login after 2 hours or so

**Comment by dmrlsn** [comment]
I'm having this very same issue right now. I tried several long-time working accounts from various residential IPs but none succeeded to login. The ones already in, once imported work fine as usual.

Any hint?

**Comment by dgrr** [comment]
Hello everyone,

Sorry for not responding to this thread I have been (and still) busy since November.
I don't know exactly what causes this error but I think we don't have any way to help you guys with that. This event occurs randomly and it's difficult to catch it when you are debugging the API with a proxy (because you don't have the proxy enabled 24/7). We don't have any way to handle it but it can be solved just by logging into the app/browser and passing the antibot test.

Right now I don't have time to debug the Instagram app to provide a well-updated API, so those kinds of bugs will still remain in the API.

**Comment by dmrlsn** [comment]
Hi there,

Unfortunately the problem of mine was not in the api. I've spent few hours trying every api out there (php, python, you name it) and none of them was able to login without challenge. 
Passing the antibot test in the browser won't work for me either, as the next time the api logins, another challenge comes out (in any api). Fresh ips/emails/accounts are in business as usual so, in order to use the old accounts, the only option for me is to pass the antibot right in the api. I've managed to solve the problem by hacking the php version and now I'm moving first steps here. As soon as I got something decent, I will be happy to share the results if anyone interested. Cheers.

**Comment by hadifarnoud** [comment]
I have the same issue. this prevents me from using goinsta at all. is there any other way to populate `.instafeed` manually from a logged-in session in browser?

**Comment by ahmdrz** [comment]
https://github.com/LevPasha/Instagram-API-python/issues/74

**Comment by felipeinf** [comment]
You have to pass the challenge, I recommend you try this example: [https://github.com/ahmdrz/goinsta/blob/master/examples/verification/main.go](https://github.com/ahmdrz/goinsta/blob/master/examples/verification/main.go)
