### ISSUE TITLE
Doen't return all followers

### ISSUE THREAD

**Issue by zaddok** [ahmdrz/goinsta#29]
With a list of followers 230 long, it is not returning all of the followers when you get the followers.

    r, err := insta.SelfUserFollowers("")

Is this connected to the undocumented `BigList` variable?

**Comment by ahmdrz** [comment]
Hi @zaddok 
Yes `BigList` variable can help us to get more than 230 followers.
This is Instagram follower pages , When you scroll in the app , after 230 followers visited , Instagram will fetch new followers using something like pagination.
We often use `SelfTotalUserFollowers()` But according to #26 We have some problem in fetching very big amount of followers.

**Comment by AlexanderProd** [comment]
I've noticed this problem in the latest version `2.4.2` as well. When paginating `user.Followers()` `.Next()` returns `false` way before all followers were retrieved. 

This happens when trying to retrieve the followers of bigger accounts, but there's no clear limit of how many can be retrieved. Sometimes it stops sooner sometimes later. 

The code I've been using is pretty straightforward. 

```
followers := user.Followers()
for followers.Next() {
	for _, user := range followers.Users {
		fmt.Println(user.Username)
                ...
	}
}
```
